apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
spec:
  replicas: 1
  selector: 
    matchLabels: 
      app: myapp
  template:
    metadata:
      name: myapp-deployment
      labels:
        app: myapp
    spec:
      containers:
       - name: helloworld-container
         image: aishwaryak01/project1
         ports:
          - containerPort: 8000
         imagePullPolicy: Always
 
      
